"""initial schema

Revision ID: 41cca761116c
Revises: 
Create Date: 2026-10-07 05:22:00.967184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cca761116c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.String(length=64), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('input_type', sa.String(length=32), nullable=False),
    sa.Column('submitted_preview', sa.Text(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('upi_risk', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_domain_id'), 'scans', ['domain_id'], unique=False)
    op.create_index(op.f('ix_scans_input_type'), 'scans', ['input_type'], unique=False)
    op.create_index(op.f('ix_scans_query_hash'), 'scans', ['query_hash'], unique=False)
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=True)
    op.create_index(op.f('ix_scans_verdict'), 'scans', ['verdict'], unique=False)
    op.create_table('qr_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('payload_type', sa.String(length=64), nullable=False),
    sa.Column('raw_preview', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_scans_scan_id'), 'qr_scans', ['scan_id'], unique=True)
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('hop_number', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_scan_id'), 'redirects', ['scan_id'], unique=False)
    op.create_table('threat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_events_scan_id'), 'threat_events', ['scan_id'], unique=False)
    op.create_index(op.f('ix_threat_events_source'), 'threat_events', ['source'], unique=False)
    op.create_index(op.f('ix_threat_events_threat_type'), 'threat_events', ['threat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_events_threat_type'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_source'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_scan_id'), table_name='threat_events')
    op.drop_table('threat_events')
    op.drop_index(op.f('ix_redirects_scan_id'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_qr_scans_scan_id'), table_name='qr_scans')
    op.drop_table('qr_scans')
    op.drop_index(op.f('ix_scans_verdict'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_query_hash'), table_name='scans')
    op.drop_index(op.f('ix_scans_input_type'), table_name='scans')
    op.drop_index(op.f('ix_scans_domain_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
